# Generated by Django 4.2.5 on 2023-10-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar2', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('change_at', models.DateField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar2.article')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar2.author')),
            ],
        ),
    ]
